export const CMD_RESET = 'CMD_RESET';
export const CMD_CHANGE_TEXTURE = 'CMD_CHANGE_TEXTURE';
export const CMD_CHANGE_MATERIAL = 'CMD_CHANGE_MATERIAL';
export const CMD_CHANGE_RESOLUTION = 'CMD_CHANGE_RESOLUTION';
export const CMD_TOGGLE = 'CMD_TOGGLE';
export const CMD_ROTATE = 'CMD_ROTATE';
