export const TEXTURE_ALBEDO = 'TEXTURE_ALBEDO';
export const TEXTURE_WATER = 'TEXTURE_WATER';
export const TEXTURE_USGS = 'TEXTURE_USGS';
export const TEXTURE_ROCKTYPES = 'TEXTURE_ROCKTYPES';
export const TEXTURE_GEOLOGICAL = 'TEXTURE_GEOLOGICAL';
export const TEXTURE_ALTITUDE = 'TEXTURE_ALTITUDE';